### PR TITLE
Additions in accordance to app requirements

### LINKED ISSUE #8: Frontend suggestions
1. I think do not show description in Miscellaneous section on the front card, the description can be really large sometimes so showing heading only will suffice
2. Add/Edit models in some of the section is really small for example Miscellaneous, Associate Scholars, Interest etc.. I think it is better to make all of them of the same size. Small modals are difficult to edit.

@nisarg73 @algomaster99 What do you think of these?

### PR DESCRIPTION
**Pull request by nisarg73**
1. Added new miscellaneous section
2. Added following fields:-

- Homepage and Interest in Associative Scholar

- Semester in Teaching Engagement

- Level in Collaboration
3. Resolved #8

### CODE REVIEW

**Comment by pradumangoyal** [comment]
Will it be possible to add an editor field in the Miscellaneous section?

**Comment by algomaster99** [comment]
@pradumangoyal I will quickly give that a try.

**Comment by pradumangoyal** [comment]
I have fixed some heading and preposition issue that I saw; other things look excellent to me. Nice work!

**Comment by algomaster99** [comment]
@pradumangoyal I will think of a better way to implement this https://github.com/IMGIITRoorkee/omniport-frontend-faculty-profile/pull/11/commits/b50e2de2ef1736aff645cf9e0ed4904a4176d080. Otherwise, everything else looks good to me as well. :tada:

**Pull request merged**
